export const industriesList = [
  "Automotive",
  "Agriculture",
  "Chemicals",
  "Construction",
  "Semiconductor & Electronics",
  "Aerospace & Defense",
  "BFSI",
  "ICT",
  "Energy & Power",
  "Consumer & Retail",
  "Packaging & Transport",
  "Food, Beverage & Nutrition",
  "Industrial Automation",
];
